# Jupyter notebook

## Cells, Markdown and code

Jupyter notebook is made up of "cells". 
There are two types of cells.

**Markdown cells** (like this one) are formatted text written in [Markdown](https://en.wikipedia.org/wiki/Markdown)
- Double click to edit markdown cell, `Ctrl`+`Enter` to render

**Code cells** (the one below) contains Python codes you can run
- Click to edit code cell, `Ctrl`+`Enter` to run code

In [2]:
print("Hello world!")

Hello world!


In [1]:
1 + 1

2

#  Python basics
## Define a variable

In [3]:
a = "A string"
print(a)

A string


## List

In [6]:
l = [1, "a", a]
print(l[2])

A string


## Dictionary

In [7]:
d = {"name": "ethylene", 
     "formular": "C2H4",
     "MW": 100}
print(d['formular'])

C2H4


# Control flows

In [12]:
for item in [1, 2, 3, 4, 5]:
    if item > 3:
        print(item)

4
5


## Function

In [10]:
def first_element(l):
    return l[0]

first_element([1, 2, 3, 4, 5])

1

# Numpy

numpy is a python module for handeling matrix operations.


In [23]:
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5],[6]])

By default, numpy object do elementwise arithmics

In [26]:
A*2

array([[2, 4],
       [6, 8]])

That means, when you try to multiply two matrix with different shape,  
numpy will try to repeat them so that their shape match

In [30]:
print(A)
print(B)
A*B

[[1 2]
 [3 4]]
[[5]
 [6]]


array([[ 5, 10],
       [18, 24]])

You can do matrix multiplications like this.

In [25]:
np.matmul(A,B)

array([[17],
       [39]])